#vick start vick-init.yaml name
#vick start command deploys the VICK controlplance in the vick namespace

apiVersion: v1
kind: Namespace
metadata:
  name: vick-system
  labels:
    creator: vick-init
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vicksvc-account
  namespace: vick-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pub-store-volume-claim
  namespace: vick-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      purpose: apim-shared-deployment
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIud3NvMi5jb20iOnsidXNlcm5hbWUiOiJ2aWNrLXNldHVwQHdzbzIuY29tIiwicGFzc3dvcmQiOiJGU3k0QFdZeTZEeldidnoiLCJlbWFpbCI6InZpY2stc2V0dXBAd3NvMi5jb20iLCJhdXRoIjoiZG1samF5MXpaWFIxY0VCM2MyOHlMbU52YlRwR1UzazBRRmRaZVRaRWVsZGlkbm89In19fQ==
kind: Secret
metadata:
  name: wso2creds
  namespace: vick-system
type: kubernetes.io/dockerconfigjson
---
#https://github.com/wso2/kubernetes-apim/blob/master/pattern-1/apim/wso2apim-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub-store
  namespace: vick-system
spec:
  selector:
    matchLabels:
      deployment: pub-store
  replicas: 1
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: pub-store
    spec:
      containers:
      - name: pub-store
        image: docker.wso2.com/wso2am:2.5.0
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - nc -z localhost 9443
          initialDelaySeconds: 150
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - nc -z localhost 9443
          initialDelaySeconds: 150
          periodSeconds: 10
        imagePullPolicy: Always
        ports:
        -
          containerPort: 8280
          protocol: "TCP"
        -
          containerPort: 8243
          protocol: "TCP"
        -
          containerPort: 9763
          protocol: "TCP"
        -
          containerPort: 9443
          protocol: "TCP"
        -
          containerPort: 5672
          protocol: "TCP"
        -
          containerPort: 9711
          protocol: "TCP"
        -
          containerPort: 9611
          protocol: "TCP"
        -
          containerPort: 7711
          protocol: "TCP"
        -
          containerPort: 7611
          protocol: "TCP"
        volumeMounts:
 #       - name: apim-storage-volume
 #         mountPath: /home/wso2carbon/wso2am-2.5.0/repository/deployment/server
 #       - name: apim-conf
 #         mountPath: /home/wso2carbon/kubernetes-volumes/am/conf
 #       - name: apim-conf-datasources
 #         mountPath: /home/wso2carbon/kubernetes-volumes/am/conf/datasources
      serviceAccountName: "vicksvc-account"
      imagePullSecrets:
      - name: wso2creds
      volumes:
 #     - name: apim-storage-volume
 #       persistentVolumeClaim:
 #         claimName: pub-store-volume-claim
 #     - name: apim-conf
 #       configMap:
 #         name: apim-conf
 #     - name: apim-conf-datasources
 #       configMap:
 #         name: apim-conf-datasources
---
#https://github.com/wso2/kubernetes-apim/blob/master/pattern-1/apim/wso2apim-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pub-store
  labels:
    app: pub-store
  namespace: vick-system
spec:
  # label keys and values that must match in order to receive traffic for this service
  selector:
    deployment: pub-store
  ports:
    # ports that this service should serve on
    -
      name: pass-through-http
      protocol: TCP
      port: 8280
    -
      name: pass-through-https
      protocol: TCP
      port: 8243
    -
      name: servlet-http
      protocol: TCP
      port: 9763
    -
      name: servlet-https
      protocol: TCP
      port: 9443
---
